from enum import Enum

class TicketEnum(str, Enum):
    FETCH_USER_CREDS_EMAIL = 'FETCH_USER_CREDS_EMAIL'
    FETCH_USER_CREDS_UNAME = 'FETCH_USER_CREDS_UNAME'
    REGISTER_NEW_USER = 'REGISTER_NEW_USER'